# Generated by Django 2.2.4 on 2019-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('categroy', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('replace', models.CharField(max_length=50)),
            ],
        ),
    ]
