# Generated by Django 2.2.4 on 2019-08-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categroy',
            new_name='category',
        ),
    ]
